# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Misha Rubanov
email: misha.rubanov.1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Molecular, software, and robotics programmer interested in building novel tools to enable scaled, robust, and
  modelable experiments. I enjoy being on the interface between science and engineering, be it via
  experimental/SOP design, building custom UIs for other scientists, or improving developer interfaces for
  custom SDKs. My experience in molecular programming has given me a unique lens in which to apply a
  programming mindset towards problems in a wide variety of fields.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed
# main branch of choice (from readme)
remote_theme: "jekyll/minima@1e8a445"
minima:
  skin: dark
  nav_pages:
    - CV.md
    - Publications.md
    - bookshelf.md
    - code.md
    - dashboard.md
  social_links:
    - title: Misha's GitHub
      icon: github
      url: "https://github.com/MishaRubanov"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/misha-rubanov/"
    - title: CV
      icon: cv.svg
      url: "https://misharubanov.com/CV.pdf"

author:
  name: Misha Rubanov
  email: "misha.rubanov.1@com"

include:
  - _jupyter

collections:
  jupyter:
    output: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
