name: Fetch HTML Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch-html-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Checkout private repository
        uses: actions/checkout@v2
        with:
          repository: MishaRubanov/RDTattoo
          token: ${{ secrets.GITHUB_TOKEN }}
          path: private-repo

      - name: Debug checkout private repository step
        run: |
          pwd
          ls -la

      - name: Copy HTML files
        run: |
          mkdir -p copied_html_files
          cp private-repo/*.html copied_html_files/

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add copied_html_files/*.html
          git commit -m 'Copy HTML files from private repository'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}